export const roles = ['Administrador', 'Gestor', 'Vendedor', 'Atendimento', 'Financeiro'];
const f = (key, label, type = 'text', extra = {}) => ({ key, label, type, ...extra });
const name = (label = 'Nome') => f('name', label, 'text', { required: true });
const owner = f('owner', 'Responsável', 'user');
const notes = f('notes', 'Observações', 'textarea');
const status = options => f('status', 'Status', 'select', { options, required: true });
const link = (key, label, entity) => f(key, label, 'relation', { entity });
const contact = [f('email', 'E-mail', 'email'), f('phone', 'Telefone / WhatsApp', 'tel')];
const address = [f('document', 'CPF / CNPJ'), f('address', 'Endereço completo'), f('city', 'Cidade'), f('state', 'UF'), f('zip', 'CEP'), f('tags', 'Tags (separadas por vírgula)')];
const customer = link('clientId', 'Cliente', 'clients');
const amount = f('amount', 'Valor (R$)', 'number', { min: 0 });
export const modules = {
leads: { title: 'Leads', singular: 'lead', icon: '◎', description: 'Da primeira conversa à próxima oportunidade.', fields: [name(), ...contact, link('companyId', 'Empresa', 'companies'), f('source', 'Origem', 'select', { options: ['Formulário', 'Indicação', 'Google', 'Meta', 'Site', 'Importação', 'Prospecção', 'Outro'] }), status(['Novo', 'Em contato', 'Qualificado', 'Desqualificado', 'Convertido']), f('score', 'Qualificação (0–100)', 'number', { min: 0, max: 100 }), owner, f('tags', 'Tags'), notes] },
clients: { title: 'Clientes', singular: 'cliente', icon: '♙', description: 'Relacionamentos, contatos e histórico em um só lugar.', fields: [name(), f('personType', 'Tipo', 'select', { options: ['Pessoa física', 'Pessoa jurídica'] }), ...contact, ...address, link('companyId', 'Empresa', 'companies'), f('segment', 'Segmento'), owner, status(['Ativo', 'Em acompanhamento', 'Inativo']), notes] },
companies: { title: 'Empresas', singular: 'empresa', icon: '▦', description: 'Organize as empresas e seus relacionamentos.', fields: [name('Razão social'), f('tradeName', 'Nome fantasia'), ...contact, ...address, f('segment', 'Segmento'), f('website', 'Site', 'url'), owner, notes] },
opportunities: { title: 'Oportunidades', singular: 'oportunidade', icon: '◇', description: 'Negociações com valor, responsável e próximo passo.', fields: [name('Título'), customer, link('leadId', 'Lead', 'leads'), owner, amount, f('stage', 'Etapa', 'stage', { required: true }), f('probability', 'Probabilidade (%)', 'number', { min: 0, max: 100 }), f('closeDate', 'Previsão de fechamento', 'date'), f('lostReason', 'Motivo de perda'), notes] },
tasks: { title: 'Tarefas', singular: 'tarefa', icon: '☑', description: 'Cada relacionamento com uma próxima ação.', fields: [name('Título'), customer, link('leadId', 'Lead', 'leads'), owner, f('dueDate', 'Prazo', 'datetime-local', { required: true }), f('priority', 'Prioridade', 'select', { options: ['Normal', 'Alta', 'Urgente'] }), status(['Pendente', 'Em andamento', 'Concluída']), notes] },
events: { title: 'Agenda', singular: 'compromisso', icon: '▣', description: 'Reuniões e compromissos da sua equipe.', fields: [name('Título'), customer, owner, f('start', 'Início', 'datetime-local', { required: true }), f('end', 'Fim', 'datetime-local', { required: true }), f('location', 'Local / link'), status(['Agendado', 'Realizado', 'Cancelado']), notes] },
activities: { title: 'Comunicação', singular: 'interação', icon: '☏', description: 'Registre conversas, ligações e próximos passos.', fields: [name('Assunto'), customer, link('leadId', 'Lead', 'leads'), f('channel', 'Canal', 'select', { options: ['Ligação', 'E-mail', 'WhatsApp', 'SMS', 'Reunião', 'Nota'] }), f('direction', 'Direção', 'select', { options: ['Recebida', 'Realizada'] }), f('date', 'Data', 'datetime-local', { required: true }), owner, notes] },
proposals: { title: 'Propostas', singular: 'proposta', icon: '▤', description: 'Do orçamento à aprovação, com versões preservadas.', fields: [name('Título'), customer, link('opportunityId', 'Oportunidade', 'opportunities'), owner, f('validUntil', 'Validade', 'date'), status(['Rascunho', 'Enviada', 'Aprovada', 'Recusada', 'Expirada']), f('discount', 'Desconto (R$)', 'number', { min: 0 }), f('terms', 'Condições comerciais', 'textarea'), notes], lines: true },
orders: { title: 'Pedidos', singular: 'pedido', icon: '▧', description: 'Acompanhe a entrega de cada venda.', fields: [name('Título'), customer, link('proposalId', 'Proposta', 'proposals'), owner, f('deliveryDate', 'Previsão de entrega', 'date'), status(['Confirmado', 'Em execução', 'Concluído', 'Cancelado']), f('discount', 'Desconto (R$)', 'number', { min: 0 }), notes], lines: true },
products: { title: 'Catálogo', singular: 'produto ou serviço', icon: '⊞', description: 'Produtos, serviços e preços para suas propostas.', fields: [name(), f('sku', 'Código'), f('category', 'Categoria'), f('type', 'Tipo', 'select', { options: ['Serviço', 'Produto'] }), f('price', 'Preço padrão (R$)', 'number', { required: true, min: 0 }), f('specialPrice', 'Preço especial (R$)', 'number', { min: 0 }), status(['Ativo', 'Inativo']), notes] },
tickets: { title: 'Atendimento', singular: 'chamado', icon: '◉', description: 'Resolva solicitações e acompanhe seus prazos.', fields: [name('Assunto'), customer, owner, f('priority', 'Prioridade', 'select', { options: ['Normal', 'Alta', 'Urgente'] }), status(['Aberto', 'Em atendimento', 'Aguardando cliente', 'Resolvido']), f('slaDue', 'Prazo de atendimento (SLA)', 'datetime-local', { required: true }), f('satisfaction', 'Satisfação (1–5)', 'number', { min: 1, max: 5 }), notes] },
articles: { title: 'Base de conhecimento', singular: 'artigo', icon: '▥', description: 'Respostas organizadas para um atendimento consistente.', fields: [name('Título'), f('category', 'Categoria'), status(['Rascunho', 'Publicado']), f('content', 'Conteúdo', 'textarea', { required: true })] },
campaigns: { title: 'Marketing', singular: 'campanha', icon: '⚑', description: 'Planeje campanhas, públicos e acompanhamento.', fields: [name(), f('channel', 'Canal', 'select', { options: ['E-mail', 'WhatsApp', 'Google', 'Meta', 'SMS', 'Outro'] }), f('segment', 'Tag do público'), f('startDate', 'Início', 'date'), f('budget', 'Orçamento (R$)', 'number', { min: 0 }), status(['Rascunho', 'Planejada', 'Em execução', 'Concluída', 'Cancelada']), f('message', 'Mensagem / conteúdo', 'textarea'), notes] },
automations: { title: 'Automações', singular: 'automação', icon: 'ϟ', description: 'Crie tarefas automaticamente a partir dos eventos do CRM.', fields: [name(), f('trigger', 'Quando acontecer', 'select', { options: ['Lead criado', 'Oportunidade criada', 'Oportunidade ganha', 'Chamado aberto'], required: true }), f('taskTitle', 'Título da tarefa criada', 'text', { required: true }), f('days', 'Prazo em dias', 'number', { min: 0, max: 365, required: true }), owner, status(['Ativa', 'Pausada'])] },
receivables: { title: 'Financeiro', singular: 'lançamento', icon: '$', description: 'Recebimentos, pagamentos e comissões.', fields: [name('Descrição'), customer, link('orderId', 'Pedido', 'orders'), f('type', 'Tipo', 'select', { options: ['Receita', 'Despesa'] }), amount, f('dueDate', 'Vencimento', 'date', { required: true }), status(['Pendente', 'Pago', 'Cancelado']), f('paidDate', 'Data de pagamento', 'date'), owner, f('commission', 'Comissão (%)', 'number', { min: 0, max: 100 }), notes] },
};
export const defaultSettings = { name: 'VNKB CRM', businessName: '', stages: [{ id: 'new', name: 'Prospecção', probability: 10 }, { id: 'qualified', name: 'Qualificação', probability: 30 }, { id: 'proposal', name: 'Proposta', probability: 60 }, { id: 'negotiation', name: 'Negociação', probability: 80 }, { id: 'won', name: 'Ganho', probability: 100 }, { id: 'lost', name: 'Perdido', probability: 0 }], proposalTerms: 'Proposta sujeita à aprovação das condições comerciais.', autoAssign: true, captureEnabled: false };
export const roleModules = {
Administrador: Object.keys(modules), Gestor: Object.keys(modules),
Vendedor: ['leads', 'clients', 'companies', 'opportunities', 'tasks', 'events', 'activities', 'proposals', 'orders', 'products', 'articles'],
Atendimento: ['clients', 'companies', 'tasks', 'events', 'activities', 'tickets', 'articles'],
Financeiro: ['clients', 'companies', 'orders', 'products', 'receivables', 'tasks', 'events'],
};
export function totals(items = [], discount = 0) {
 const subtotal = Math.round(items.reduce((n, i) => n + Number(i.quantity) * Number(i.price), 0) * 100) / 100;
 if (Number(discount) > subtotal) throw new Error('O desconto não pode superar o subtotal.');
 return { subtotal, amount: Math.round((subtotal - Number(discount || 0)) * 100) / 100 };
}

// ERP: cadastros compartilhados com o CRM, sem duplicar clientes e produtos.
Object.assign(modules, {
 suppliers: { title: 'Fornecedores', singular: 'fornecedor', icon: '▦', description: 'Parceiros de compras e prestação de serviços.', fields: [name(), ...contact, ...address, notes] },
 purchases: { title: 'Compras', singular: 'compra', icon: '▧', description: 'Pedidos de compra e despesas relacionadas.', fields: [name('Descrição'), link('supplierId', 'Fornecedor', 'suppliers'), owner, f('deliveryDate', 'Entrega prevista', 'date'), status(['Solicitada', 'Aprovada', 'Recebida', 'Cancelada']), f('discount', 'Desconto (R$)', 'number', { min: 0 }), notes], lines: true },
 movements: { title: 'Estoque', singular: 'movimentação', icon: '⊞', description: 'Entradas, saídas e saldo calculado por produto.', fields: [name('Descrição'), link('productId', 'Produto', 'products'), f('type', 'Tipo', 'select', { options: ['Entrada', 'Saída'], required: true }), f('quantity', 'Quantidade', 'number', { min: 0.001, required: true }), f('date', 'Data', 'date', { required: true }), notes] },
 invoices: { title: 'Fiscal', singular: 'documento fiscal', icon: '▤', description: 'Registro e acompanhamento de documentos fiscais.', fields: [name('Número / identificação'), customer, link('orderId', 'Pedido', 'orders'), f('type', 'Tipo', 'select', { options: ['NFe', 'NFSe', 'CTe', 'Outro'] }), amount, f('date', 'Emissão', 'date', { required: true }), f('accessKey', 'Chave de acesso'), status(['Pendente', 'Emitida externamente', 'Cancelada']), notes] },
 employees: { title: 'Pessoas e RH', singular: 'colaborador', icon: '♙', description: 'Equipe, vínculo e informações de trabalho.', fields: [name(), ...contact, f('document', 'CPF'), f('job', 'Cargo'), f('department', 'Departamento'), f('salary', 'Salário (R$)', 'number', { min: 0 }), f('admissionDate', 'Admissão', 'date'), status(['Ativo', 'Férias', 'Afastado', 'Desligado']), notes] },
 payroll: { title: 'Folha e benefícios', singular: 'lançamento de folha', icon: '$', description: 'Controle interno de salários, benefícios e descontos.', fields: [name('Descrição'), link('employeeId', 'Colaborador', 'employees'), f('month', 'Competência', 'month', { required: true }), f('type', 'Tipo', 'select', { options: ['Salário', 'Benefício', 'Desconto', 'Férias', 'Décimo terceiro'] }), amount, status(['Previsto', 'Pago']), notes] },
 vehicles: { title: 'Frota', singular: 'veículo', icon: '◇', description: 'Veículos, documentos e disponibilidade.', fields: [name('Modelo / identificação'), f('plate', 'Placa', 'text', { required: true }), f('year', 'Ano', 'number', { min: 1900, max: 2200 }), f('odometer', 'Quilometragem', 'number', { min: 0 }), f('licenseDate', 'Vencimento do licenciamento', 'date'), status(['Disponível', 'Em uso', 'Em manutenção', 'Inativo']), notes] },
 fleetCosts: { title: 'Despesas da frota', singular: 'despesa da frota', icon: '$', description: 'Manutenção, abastecimento e custos por veículo.', fields: [name('Descrição'), link('vehicleId', 'Veículo', 'vehicles'), f('type', 'Tipo', 'select', { options: ['Abastecimento', 'Manutenção', 'Seguro', 'Licenciamento', 'Multa', 'Outro'] }), f('date', 'Data', 'date', { required: true }), amount, f('odometer', 'Quilometragem', 'number', { min: 0 }), notes] },
 contracts: { title: 'Contratos', singular: 'contrato', icon: '▥', description: 'Vigência, valores e documentos dos seus contratos.', fields: [name('Título'), customer, link('supplierId', 'Fornecedor', 'suppliers'), f('type', 'Tipo', 'select', { options: ['Cliente', 'Fornecedor'] }), f('startDate', 'Início', 'date'), f('endDate', 'Fim', 'date'), amount, f('frequency', 'Periodicidade', 'select', { options: ['Único', 'Mensal', 'Anual'] }), status(['Rascunho', 'Ativo', 'Encerrado', 'Cancelado']), notes] },
 documents: { title: 'Documentos', singular: 'documento', icon: '▤', description: 'Documentos administrativos e anexos organizados.', fields: [name('Título'), customer, f('category', 'Categoria'), f('expiryDate', 'Validade', 'date'), owner, notes] },
});
roleModules.Administrador = Object.keys(modules);
roleModules.Gestor = Object.keys(modules);
roleModules.Financeiro.push('suppliers', 'purchases', 'invoices', 'contracts');
defaultSettings.name = 'VNKB Gestão';
